"""Add ondelete SET NULL to zmapowany_do_id

Revision ID: 3a9de06c28ad
Revises: 
Create Date: 2025-05-23 22:09:46.932818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9de06c28ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_logbledow_timestamp'), 'logbledow', ['timestamp'], unique=False)
    # op.create_index(op.f('ix_paragon_data_wyslania'), 'paragon', ['data_wyslania'], unique=False)
    # op.create_index(op.f('ix_paragon_status_przetwarzania'), 'paragon', ['status_przetwarzania'], unique=False)
    # op.add_column('produkt', sa.Column('ilosc_na_paragonie', sa.Integer(), nullable=True))
    # op.add_column('produkt', sa.Column('aktualna_ilosc', sa.Integer(), nullable=True))
    # op.add_column('produkt', sa.Column('status_mapowania', sa.Enum('OCZEKUJE', 'ZMAPOWANY', 'NOWY', 'IGNOROWANY', name='statusmapowania'), nullable=False))
    # op.add_column('produkt', sa.Column('sugestie_mapowania', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # op.add_column('produkt', sa.Column('zmapowany_do_id', sa.Integer(), nullable=True))
    # op.alter_column('produkt', 'cena',
    #            existing_type=sa.FLOAT(),
    #            type_=sa.Numeric(precision=10, scale=2),
    #            existing_nullable=False)
    # op.alter_column('produkt', 'paragon_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.create_index(op.f('ix_produkt_data_dodania'), 'produkt', ['data_dodania'], unique=False)
    # op.create_index(op.f('ix_produkt_paragon_id'), 'produkt', ['paragon_id'], unique=False)
    # op.create_foreign_key(None, 'produkt', 'produkt', ['zmapowany_do_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'produkt', type_='foreignkey')
    # op.drop_index(op.f('ix_produkt_paragon_id'), table_name='produkt')
    # op.drop_index(op.f('ix_produkt_data_dodania'), table_name='produkt')
    # op.alter_column('produkt', 'paragon_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.alter_column('produkt', 'cena',
    #            existing_type=sa.Numeric(precision=10, scale=2),
    #            type_=sa.FLOAT(),
    #            existing_nullable=False)
    # op.drop_column('produkt', 'zmapowany_do_id')
    # op.drop_column('produkt', 'sugestie_mapowania')
    # op.drop_column('produkt', 'status_mapowania')
    # op.drop_column('produkt', 'aktualna_ilosc')
    # op.drop_column('produkt', 'ilosc_na_paragonie')
    # op.drop_index(op.f('ix_paragon_status_przetwarzania'), table_name='paragon')
    # op.drop_index(op.f('ix_paragon_data_wyslania'), table_name='paragon')
    # op.drop_index(op.f('ix_logbledow_timestamp'), table_name='logbledow')
    # ### end Alembic commands ###
    pass
