"""initial

Revision ID: 80460c2ab587
Revises: 
Create Date: 2025-05-24 09:37:48.943043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80460c2ab587'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logbledow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('poziom', sa.Enum('ERROR', 'WARNING', 'INFO', name='poziomlogu'), nullable=False),
    sa.Column('modul_aplikacji', sa.String(), nullable=False),
    sa.Column('funkcja', sa.String(), nullable=False),
    sa.Column('komunikat_bledu', sa.String(), nullable=False),
    sa.Column('szczegoly_techniczne', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logbledow_timestamp'), 'logbledow', ['timestamp'], unique=False)
    op.create_table('paragon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa_pliku_oryginalnego', sa.String(), nullable=False),
    sa.Column('sciezka_pliku_na_serwerze', sa.String(), nullable=False),
    sa.Column('mime_type_pliku', sa.String(), nullable=False),
    sa.Column('sciezka_miniatury', sa.String(), nullable=True),
    sa.Column('status_przetwarzania', sa.Enum('OCZEKUJE_NA_PODGLAD', 'PODGLADNIETY_OCZEKUJE_NA_PRZETWORZENIE', 'PRZETWARZANY_OCR', 'PRZETWARZANY_AI', 'PRZETWORZONY_OK', 'PRZETWORZONY_BLAD', name='statusparagonu'), nullable=False),
    sa.Column('data_wyslania', sa.DateTime(), nullable=False),
    sa.Column('data_przetworzenia', sa.DateTime(), nullable=True),
    sa.Column('blad_przetwarzania', sa.String(), nullable=True),
    sa.Column('status_szczegolowy', sa.String(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True, server_default='0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paragon_data_wyslania'), 'paragon', ['data_wyslania'], unique=False)
    op.create_index(op.f('ix_paragon_status_przetwarzania'), 'paragon', ['status_przetwarzania'], unique=False)
    op.create_table('produkt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(), nullable=False),
    sa.Column('kategoria', sa.Enum('Spożywcze', 'Chemia', 'Kosmetyki', 'Napoje', 'Słodycze', 'Pieczywo', 'Warzywa', 'Owoce', 'Inne', name='kategoriaproduktu'), nullable=False),
    sa.Column('cena', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_waznosci', sa.DateTime(), nullable=True),
    sa.Column('paragon_id', sa.Integer(), nullable=True),
    sa.Column('data_dodania', sa.DateTime(), nullable=False),
    sa.Column('data_aktualizacji', sa.DateTime(), nullable=False),
    sa.Column('ilosc_na_paragonie', sa.Integer(), nullable=True),
    sa.Column('aktualna_ilosc', sa.Integer(), nullable=True),
    sa.Column('status_mapowania', sa.Enum('OCZEKUJE', 'ZMAPOWANY', 'NOWY', 'IGNOROWANY', name='statusmapowania'), nullable=False),
    sa.Column('sugestie_mapowania', sa.String(), nullable=True),
    sa.Column('zmapowany_do_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paragon_id'], ['paragon.id'], ),
    sa.ForeignKeyConstraint(['zmapowany_do_id'], ['produkt.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produkt_data_aktualizacji'), 'produkt', ['data_aktualizacji'], unique=False)
    op.create_index(op.f('ix_produkt_data_dodania'), 'produkt', ['data_dodania'], unique=False)
    op.create_index(op.f('ix_produkt_paragon_id'), 'produkt', ['paragon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produkt_paragon_id'), table_name='produkt')
    op.drop_index(op.f('ix_produkt_data_dodania'), table_name='produkt')
    op.drop_index(op.f('ix_produkt_data_aktualizacji'), table_name='produkt')
    op.drop_table('produkt')
    op.drop_index(op.f('ix_paragon_status_przetwarzania'), table_name='paragon')
    op.drop_index(op.f('ix_paragon_data_wyslania'), table_name='paragon')
    op.drop_table('paragon')
    op.drop_index(op.f('ix_logbledow_timestamp'), table_name='logbledow')
    op.drop_table('logbledow')
    # ### end Alembic commands ###
